### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by ozkilim** [ashishthomaschempolil/Medical-Image-Captioning-on-Chest-X-rays#1]
Dear Ashish,

Thanks very much for the Blog on image captioning! 

I was trying to reproduce your work and wanted to know if you had a script to turn the XML files into the pandas dataframe because it's not included in the Github page. Or did you do it all on the regex site?

Best,
Oz

**Comment by ashishthomaschempolil** [comment]
Hi, its in the eda ipynb file. Check for get_info function

**Comment by ozkilim** [comment]
Thanks very much!
